package tests
{
   public class AngryBirdsFacebookTest
   {
       
      
      private var sData:Object;
      
      private var mAngryBirdsFacebook:IAngryBirdsFacebook;
      
      public function AngryBirdsFacebookTest()
      {
         super();
      }
      
      [BeforeClass]
      public static function setUpBeforeClass() : void
      {
      }
      
      [AfterClass]
      public static function tearDownAfterClass() : void
      {
      }
      
      [Before]
      public function setUp() : void
      {
         this.sData = {
            "user":{
               "userId":100002999593950,
               "login":"0ce003c66d383777f47dde1cb919820b48ef23dd",
               "name":"Jonas",
               "lastName":"Nyman",
               "vb":false,
               "ap":false,
               "tutorials":["END_RAFFLE_EASTER_2013"],
               "TPId":"rkoXHDFWcKua8x3FGiaIInCy_H4"
            },
            "apiVersion":1,
            "friends":{
               "totalItemCount":50,
               "items":[{
                  "u":542062409,
                  "n":"Chico",
                  "l":"Spencer",
                  "r":1,
                  "s":422,
                  "me":1,
                  "a":"B20004-C10013-H30016-E40008-M50007-W60011",
                  "i":false
               },{
                  "u":100000514719371,
                  "n":"Markus",
                  "l":"Moisio",
                  "r":2,
                  "s":271,
                  "me":20,
                  "a":"B20008-C10012-H30008-E40003-M50001-W60016",
                  "i":false
               },{
                  "u":583939081,
                  "n":"Lauri",
                  "l":"Hosio",
                  "r":3,
                  "s":251,
                  "me":11,
                  "a":"B20006-C10006-H30017-E40003-M50005-W60021",
                  "i":false
               },{
                  "u":675152444,
                  "n":"Marko",
                  "l":"Kalliokoski",
                  "r":4,
                  "s":175,
                  "me":0,
                  "i":false
               },{
                  "u":521658479,
                  "n":"Iikka",
                  "l":"Paavolainen",
                  "r":5,
                  "s":157,
                  "me":5,
                  "a":"B20001-C10012-W60014",
                  "i":false
               },{
                  "u":1293179000,
                  "n":"Pauli",
                  "l":"Savolainen",
                  "r":6,
                  "s":126,
                  "me":0,
                  "i":false
               },{
                  "u":528699507,
                  "n":"Antti",
                  "l":"Malmi",
                  "r":7,
                  "s":121,
                  "me":8,
                  "a":"B20001-C10006-H30011-E40002-M50005-W60009",
                  "i":false
               },{
                  "u":655535877,
                  "n":"Serdar",
                  "l":"Soganci",
                  "r":8,
                  "s":85,
                  "me":0,
                  "a":"B20006-C10008-H30020-E40004-M50008-W60017",
                  "i":false
               },{
                  "u":682352288,
                  "n":"Sami",
                  "l":"Lahtinen",
                  "r":9,
                  "s":81,
                  "me":1,
                  "i":false
               },{
                  "u":704719211,
                  "n":"Juuso",
                  "l":"Huttunen",
                  "r":10,
                  "s":80,
                  "me":2,
                  "a":"B20001-C10001",
                  "i":false
               },{
                  "u":629026893,
                  "n":"Anne",
                  "l":"Dahlgren",
                  "r":11,
                  "s":68,
                  "me":0,
                  "i":false
               },{
                  "u":615738921,
                  "n":"Juho",
                  "l":"Törhönen",
                  "r":12,
                  "s":65,
                  "me":0,
                  "a":"B20004-C10014-H30008-E40005-M50004-W60011",
                  "i":false
               },{
                  "u":644779038,
                  "n":"Ari",
                  "l":"Arnbjörnsson",
                  "r":13,
                  "s":64,
                  "me":3,
                  "i":false
               },{
                  "u":514852999,
                  "n":"Tuuli",
                  "l":"Juntunen",
                  "r":14,
                  "s":54,
                  "me":0,
                  "a":"B20006-C10003-H30024-M50007-W60023",
                  "i":false
               },{
                  "u":726573085,
                  "n":"Stefan",
                  "l":"Hauk",
                  "r":15,
                  "s":37,
                  "me":1,
                  "i":false
               },{
                  "u":635436490,
                  "n":"Saara",
                  "l":"Bergström",
                  "r":16,
                  "s":35,
                  "me":0,
                  "i":false
               },{
                  "u":507158105,
                  "n":"Simo",
                  "l":"Rajamäki",
                  "r":17,
                  "s":28,
                  "me":1,
                  "a":"B20001-C10001-H30002-E40001",
                  "i":false
               },{
                  "u":1789006230,
                  "n":"Petri",
                  "l":"Järvilehto",
                  "r":18,
                  "s":27,
                  "me":0,
                  "a":"B20003-C10001-H30001-E40001-M50001-W60001",
                  "i":false
               },{
                  "u":593928817,
                  "n":"Jessica",
                  "l":"Guisquet",
                  "r":19,
                  "s":25,
                  "me":0,
                  "i":false
               },{
                  "u":100003066875714,
                  "n":"Razr",
                  "l":"Coolberg",
                  "r":20,
                  "s":25,
                  "me":0,
                  "i":false
               },{
                  "u":1049365917,
                  "n":"Risto",
                  "l":"Holmström",
                  "r":21,
                  "s":18,
                  "me":0,
                  "i":false
               },{
                  "u":705485221,
                  "n":"Joonas",
                  "l":"Mäkilä",
                  "r":22,
                  "s":15,
                  "me":0,
                  "i":false
               },{
                  "u":831420759,
                  "n":"Agata",
                  "l":"Lukasiewicz",
                  "r":23,
                  "s":15,
                  "me":0,
                  "a":"B20001-C10001-H30022-E40006-M50010",
                  "i":false
               },{
                  "u":100000407635394,
                  "n":"Timo",
                  "l":"Maaranen",
                  "r":24,
                  "s":12,
                  "me":0,
                  "i":false
               },{
                  "u":654660602,
                  "n":"Manuel",
                  "l":"Somonte",
                  "r":25,
                  "s":11,
                  "me":1,
                  "a":"B20011-C10012-H30014-E40007-M50007-W60019",
                  "i":false
               },{
                  "u":721005129,
                  "n":"Robert",
                  "l":"Bogacki",
                  "r":26,
                  "s":9,
                  "me":17,
                  "i":false
               },{
                  "u":662533881,
                  "n":"Ville",
                  "l":"Räisänen",
                  "r":27,
                  "s":8,
                  "me":0,
                  "i":false
               },{
                  "u":100003381966069,
                  "n":"Bart",
                  "l":"van Paassen",
                  "r":28,
                  "s":8,
                  "me":0,
                  "i":false
               },{
                  "u":614199569,
                  "n":"Salla",
                  "l":"Hakko",
                  "r":29,
                  "s":6,
                  "me":0,
                  "i":false
               },{
                  "u":509344689,
                  "n":"Jessica",
                  "l":"Virtanen",
                  "r":30,
                  "s":4,
                  "me":0,
                  "i":false
               },{
                  "u":523449884,
                  "n":"Piotr",
                  "l":"Gutaker",
                  "r":31,
                  "s":3,
                  "me":0,
                  "i":false
               },{
                  "u":1426892960,
                  "n":"Ramine",
                  "l":"Darabiha",
                  "r":32,
                  "s":3,
                  "me":0,
                  "i":false
               },{
                  "u":213993,
                  "n":"Sini",
                  "l":"Matikainen",
                  "r":33,
                  "s":1,
                  "me":0,
                  "i":false
               },{
                  "u":851325036,
                  "n":"Tianyi",
                  "l":"Pan",
                  "r":34,
                  "s":0,
                  "me":0,
                  "i":false
               },{
                  "u":100002452029113,
                  "n":"Adeshina Raymond",
                  "l":"Ottun",
                  "r":35,
                  "s":0,
                  "me":0,
                  "i":false
               },{
                  "u":678597102,
                  "n":"Henrik",
                  "l":"Rinne",
                  "r":36,
                  "s":0,
                  "me":0,
                  "i":false
               },{
                  "u":749094472,
                  "n":"Τάσος",
                  "l":"Κατωπόδης",
                  "r":37,
                  "s":0,
                  "me":0,
                  "i":false
               },{
                  "u":649927710,
                  "n":"Niklas",
                  "l":"Hed",
                  "r":38,
                  "s":0,
                  "me":0,
                  "i":false
               },{
                  "u":100003061762652,
                  "n":"Shaun",
                  "l":"Connery",
                  "r":39,
                  "s":0,
                  "me":0,
                  "i":false
               },{
                  "u":1038949977,
                  "n":"Erison",
                  "l":"Silva",
                  "r":40,
                  "s":0,
                  "me":0,
                  "a":"B20001-C10001",
                  "i":false
               },{
                  "u":100002999593950,
                  "n":"Jonas",
                  "l":"Nyman",
                  "r":41,
                  "s":0,
                  "me":0,
                  "i":false
               },{
                  "u":663567656,
                  "n":"Tan",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               },{
                  "u":560086419,
                  "n":"Jonas",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               },{
                  "u":803785645,
                  "n":"Emyl",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               },{
                  "u":696859829,
                  "n":"Philip",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               },{
                  "u":1233821185,
                  "n":"Laura",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               },{
                  "u":1508470874,
                  "n":"Saara",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               },{
                  "u":702455393,
                  "n":"Eoin",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               },{
                  "u":667007902,
                  "n":"Nikolina",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               },{
                  "u":100003072344437,
                  "n":"Jonas",
                  "l":"",
                  "r":0,
                  "s":0,
                  "me":0,
                  "i":true
               }]
            },
            "dailyReward":{"rewardGiven":false},
            "state":[],
            "tournament":{"previousTournament":{
               "players":[{
                  "u":-1,
                  "n":"Red",
                  "l":"",
                  "r":1,
                  "p":592070,
                  "i":false
               },{
                  "u":-2,
                  "n":"Chuck",
                  "l":"",
                  "r":2,
                  "p":564330,
                  "i":false
               }],
               "goldTrophies":0,
               "silverTrophies":0,
               "bronzeTrophies":0,
               "priceCounts":[200,100,50,10]
            }},
            "requests":{
               "gifts":[],
               "brags":[]
            },
            "excludedUserIds":[],
            "deauthorizedUserIds":[],
            "eggs":[],
            "shopcampaigns":[],
            "abtesting":[{"ShopVisuals1":"xPlusYFreeR"},{"FreeMushroomIntroSampleEaster2013":"threeFree"}],
            "sessionid":81,
            "items":{
               "items":[{
                  "i":"BirdFood",
                  "q":5
               },{
                  "i":"Earthquake",
                  "q":5
               },{
                  "i":"ExtraBird",
                  "q":11
               },{
                  "i":"ExtraSpeed",
                  "q":5
               },{
                  "i":"LaserSight",
                  "q":5
               },{
                  "i":"MightyEagle",
                  "q":5
               },{
                  "i":"VirtualCurrency",
                  "q":444
               }],
               "ownedBundles":["VCIntro"],
               "claimableBundles":["MobileLoginPack","MushroomIntro"]
            },
            "servertime":{"time":1367229924914}
         };
         this.mAngryBirdsFacebook = new MockAngryBirdsFacebook();
      }
      
      [After]
      public function tearDown() : void
      {
         this.sData = null;
      }
      
      [Test]
      public function testInitHighScoreListManager() : void
      {
      }
   }
}
