package com.rovio.utils
{
   import flash.utils.Dictionary;
   
   public class CountryCodes
   {
      
      private static var sCountryCode:CountryCodes;
       
      
      private var mCountryCodes:Dictionary;
      
      public function CountryCodes()
      {
         this.mCountryCodes = new Dictionary();
         super();
         this.mCountryCodes["AF"] = "AFGHANISTAN";
         this.mCountryCodes["AX"] = "ÅLAND ISLANDS";
         this.mCountryCodes["AL"] = "ALBANIA";
         this.mCountryCodes["DZ"] = "ALGERIA";
         this.mCountryCodes["AS"] = "AMERICAN SAMOA";
         this.mCountryCodes["AD"] = "ANDORRA";
         this.mCountryCodes["AO"] = "ANGOLA";
         this.mCountryCodes["AI"] = "ANGUILLA";
         this.mCountryCodes["AQ"] = "ANTARCTICA";
         this.mCountryCodes["AG"] = "ANTIGUA AND BARBUDA";
         this.mCountryCodes["AR"] = "ARGENTINA";
         this.mCountryCodes["AM"] = "ARMENIA";
         this.mCountryCodes["AW"] = "ARUBA";
         this.mCountryCodes["AU"] = "AUSTRALIA";
         this.mCountryCodes["AT"] = "AUSTRIA";
         this.mCountryCodes["AZ"] = "AZERBAIJAN";
         this.mCountryCodes["BS"] = "BAHAMAS";
         this.mCountryCodes["BH"] = "BAHRAIN";
         this.mCountryCodes["BD"] = "BANGLADESH";
         this.mCountryCodes["BB"] = "BARBADOS";
         this.mCountryCodes["BY"] = "BELARUS";
         this.mCountryCodes["BE"] = "BELGIUM";
         this.mCountryCodes["BZ"] = "BELIZE";
         this.mCountryCodes["BJ"] = "BENIN";
         this.mCountryCodes["BM"] = "BERMUDA";
         this.mCountryCodes["BT"] = "BHUTAN";
         this.mCountryCodes["BO"] = "BOLIVIA, PLURINATIONAL STATE OF";
         this.mCountryCodes["BQ"] = "BONAIRE, SINT EUSTATIUS AND SABA";
         this.mCountryCodes["BA"] = "BOSNIA AND HERZEGOVINA";
         this.mCountryCodes["BW"] = "BOTSWANA";
         this.mCountryCodes["BV"] = "BOUVET ISLAND";
         this.mCountryCodes["BR"] = "BRAZIL";
         this.mCountryCodes["IO"] = "BRITISH INDIAN OCEAN TERRITORY";
         this.mCountryCodes["BN"] = "BRUNEI DARUSSALAM";
         this.mCountryCodes["BG"] = "BULGARIA";
         this.mCountryCodes["BF"] = "BURKINA FASO";
         this.mCountryCodes["BI"] = "BURUNDI";
         this.mCountryCodes["KH"] = "CAMBODIA";
         this.mCountryCodes["CM"] = "CAMEROON";
         this.mCountryCodes["CA"] = "CANADA";
         this.mCountryCodes["CV"] = "CAPE VERDE";
         this.mCountryCodes["KY"] = "CAYMAN ISLANDS";
         this.mCountryCodes["CF"] = "CENTRAL AFRICAN REPUBLIC";
         this.mCountryCodes["TD"] = "CHAD";
         this.mCountryCodes["CL"] = "CHILE";
         this.mCountryCodes["CN"] = "CHINA";
         this.mCountryCodes["CX"] = "CHRISTMAS ISLAND";
         this.mCountryCodes["CC"] = "COCOS (KEELING) ISLANDS";
         this.mCountryCodes["CO"] = "COLOMBIA";
         this.mCountryCodes["KM"] = "COMOROS";
         this.mCountryCodes["CG"] = "CONGO";
         this.mCountryCodes["CD"] = "CONGO, THE DEMOCRATIC REPUBLIC OF THE";
         this.mCountryCodes["CK"] = "COOK ISLANDS";
         this.mCountryCodes["CR"] = "COSTA RICA";
         this.mCountryCodes["CI"] = "CÔTE D\'IVOIRE";
         this.mCountryCodes["HR"] = "CROATIA";
         this.mCountryCodes["CU"] = "CUBA";
         this.mCountryCodes["CW"] = "CURAÇAO";
         this.mCountryCodes["CY"] = "CYPRUS";
         this.mCountryCodes["CZ"] = "CZECH REPUBLIC";
         this.mCountryCodes["DK"] = "DENMARK";
         this.mCountryCodes["DJ"] = "DJIBOUTI";
         this.mCountryCodes["DM"] = "DOMINICA";
         this.mCountryCodes["DO"] = "DOMINICAN REPUBLIC";
         this.mCountryCodes["EC"] = "ECUADOR";
         this.mCountryCodes["EG"] = "EGYPT";
         this.mCountryCodes["SV"] = "EL SALVADOR";
         this.mCountryCodes["GQ"] = "EQUATORIAL GUINEA";
         this.mCountryCodes["ER"] = "ERITREA";
         this.mCountryCodes["EE"] = "ESTONIA";
         this.mCountryCodes["ET"] = "ETHIOPIA";
         this.mCountryCodes["FK"] = "FALKLAND ISLANDS (MALVINAS)";
         this.mCountryCodes["FO"] = "FAROE ISLANDS";
         this.mCountryCodes["FJ"] = "FIJI";
         this.mCountryCodes["FI"] = "FINLAND";
         this.mCountryCodes["FR"] = "FRANCE";
         this.mCountryCodes["GF"] = "FRENCH GUIANA";
         this.mCountryCodes["PF"] = "FRENCH POLYNESIA";
         this.mCountryCodes["TF"] = "FRENCH SOUTHERN TERRITORIES";
         this.mCountryCodes["GA"] = "GABON";
         this.mCountryCodes["GM"] = "GAMBIA";
         this.mCountryCodes["GE"] = "GEORGIA";
         this.mCountryCodes["DE"] = "GERMANY";
         this.mCountryCodes["GH"] = "GHANA";
         this.mCountryCodes["GI"] = "GIBRALTAR";
         this.mCountryCodes["GR"] = "GREECE";
         this.mCountryCodes["GL"] = "GREENLAND";
         this.mCountryCodes["GD"] = "GRENADA";
         this.mCountryCodes["GP"] = "GUADELOUPE";
         this.mCountryCodes["GU"] = "GUAM";
         this.mCountryCodes["GT"] = "GUATEMALA";
         this.mCountryCodes["GG"] = "GUERNSEY";
         this.mCountryCodes["GN"] = "GUINEA";
         this.mCountryCodes["GW"] = "GUINEA-BISSAU";
         this.mCountryCodes["GY"] = "GUYANA";
         this.mCountryCodes["HT"] = "HAITI";
         this.mCountryCodes["HM"] = "HEARD ISLAND AND MCDONALD ISLANDS";
         this.mCountryCodes["VA"] = "HOLY SEE (VATICAN CITY STATE)";
         this.mCountryCodes["HN"] = "HONDURAS";
         this.mCountryCodes["HK"] = "HONG KONG";
         this.mCountryCodes["HU"] = "HUNGARY";
         this.mCountryCodes["IS"] = "ICELAND";
         this.mCountryCodes["IN"] = "INDIA";
         this.mCountryCodes["ID"] = "INDONESIA";
         this.mCountryCodes["IR"] = "IRAN, ISLAMIC REPUBLIC OF";
         this.mCountryCodes["IQ"] = "IRAQ";
         this.mCountryCodes["IE"] = "IRELAND";
         this.mCountryCodes["IM"] = "ISLE OF MAN";
         this.mCountryCodes["IL"] = "ISRAEL";
         this.mCountryCodes["IT"] = "ITALY";
         this.mCountryCodes["JM"] = "JAMAICA";
         this.mCountryCodes["JP"] = "JAPAN";
         this.mCountryCodes["JE"] = "JERSEY";
         this.mCountryCodes["JO"] = "JORDAN";
         this.mCountryCodes["KZ"] = "KAZAKHSTAN";
         this.mCountryCodes["KE"] = "KENYA";
         this.mCountryCodes["KI"] = "KIRIBATI";
         this.mCountryCodes["KP"] = "KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF";
         this.mCountryCodes["KR"] = "KOREA, REPUBLIC OF";
         this.mCountryCodes["KW"] = "KUWAIT";
         this.mCountryCodes["KG"] = "KYRGYZSTAN";
         this.mCountryCodes["LA"] = "LAO PEOPLE\'S DEMOCRATIC REPUBLIC";
         this.mCountryCodes["LV"] = "LATVIA";
         this.mCountryCodes["LB"] = "LEBANON";
         this.mCountryCodes["LS"] = "LESOTHO";
         this.mCountryCodes["LR"] = "LIBERIA";
         this.mCountryCodes["LY"] = "LIBYA";
         this.mCountryCodes["LI"] = "LIECHTENSTEIN";
         this.mCountryCodes["LT"] = "LITHUANIA";
         this.mCountryCodes["LU"] = "LUXEMBOURG";
         this.mCountryCodes["MO"] = "MACAO";
         this.mCountryCodes["MK"] = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF";
         this.mCountryCodes["MG"] = "MADAGASCAR";
         this.mCountryCodes["MW"] = "MALAWI";
         this.mCountryCodes["MY"] = "MALAYSIA";
         this.mCountryCodes["MV"] = "MALDIVES";
         this.mCountryCodes["ML"] = "MALI";
         this.mCountryCodes["MT"] = "MALTA";
         this.mCountryCodes["MH"] = "MARSHALL ISLANDS";
         this.mCountryCodes["MQ"] = "MARTINIQUE";
         this.mCountryCodes["MR"] = "MAURITANIA";
         this.mCountryCodes["MU"] = "MAURITIUS";
         this.mCountryCodes["YT"] = "MAYOTTE";
         this.mCountryCodes["MX"] = "MEXICO";
         this.mCountryCodes["FM"] = "MICRONESIA, FEDERATED STATES OF";
         this.mCountryCodes["MD"] = "MOLDOVA, REPUBLIC OF";
         this.mCountryCodes["MC"] = "MONACO";
         this.mCountryCodes["MN"] = "MONGOLIA";
         this.mCountryCodes["ME"] = "MONTENEGRO";
         this.mCountryCodes["MS"] = "MONTSERRAT";
         this.mCountryCodes["MA"] = "MOROCCO";
         this.mCountryCodes["MZ"] = "MOZAMBIQUE";
         this.mCountryCodes["MM"] = "MYANMAR";
         this.mCountryCodes["NA"] = "NAMIBIA";
         this.mCountryCodes["NR"] = "NAURU";
         this.mCountryCodes["NP"] = "NEPAL";
         this.mCountryCodes["NL"] = "NETHERLANDS";
         this.mCountryCodes["NC"] = "NEW CALEDONIA";
         this.mCountryCodes["NZ"] = "NEW ZEALAND";
         this.mCountryCodes["NI"] = "NICARAGUA";
         this.mCountryCodes["NE"] = "NIGER";
         this.mCountryCodes["NG"] = "NIGERIA";
         this.mCountryCodes["NU"] = "NIUE";
         this.mCountryCodes["NF"] = "NORFOLK ISLAND";
         this.mCountryCodes["MP"] = "NORTHERN MARIANA ISLANDS";
         this.mCountryCodes["NO"] = "NORWAY";
         this.mCountryCodes["OM"] = "OMAN";
         this.mCountryCodes["PK"] = "PAKISTAN";
         this.mCountryCodes["PW"] = "PALAU";
         this.mCountryCodes["PS"] = "PALESTINE, STATE OF";
         this.mCountryCodes["PA"] = "PANAMA";
         this.mCountryCodes["PG"] = "PAPUA NEW GUINEA";
         this.mCountryCodes["PY"] = "PARAGUAY";
         this.mCountryCodes["PE"] = "PERU";
         this.mCountryCodes["PH"] = "PHILIPPINES";
         this.mCountryCodes["PN"] = "PITCAIRN";
         this.mCountryCodes["PL"] = "POLAND";
         this.mCountryCodes["PT"] = "PORTUGAL";
         this.mCountryCodes["PR"] = "PUERTO RICO";
         this.mCountryCodes["QA"] = "QATAR";
         this.mCountryCodes["RE"] = "RÉUNION";
         this.mCountryCodes["RO"] = "ROMANIA";
         this.mCountryCodes["RU"] = "RUSSIAN FEDERATION";
         this.mCountryCodes["RW"] = "RWANDA";
         this.mCountryCodes["BL"] = "SAINT BARTHÉLEMY";
         this.mCountryCodes["SH"] = "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA";
         this.mCountryCodes["KN"] = "SAINT KITTS AND NEVIS";
         this.mCountryCodes["LC"] = "SAINT LUCIA";
         this.mCountryCodes["MF"] = "SAINT MARTIN (FRENCH PART)";
         this.mCountryCodes["PM"] = "SAINT PIERRE AND MIQUELON";
         this.mCountryCodes["VC"] = "SAINT VINCENT AND THE GRENADINES";
         this.mCountryCodes["WS"] = "SAMOA";
         this.mCountryCodes["SM"] = "SAN MARINO";
         this.mCountryCodes["ST"] = "SAO TOME AND PRINCIPE";
         this.mCountryCodes["SA"] = "SAUDI ARABIA";
         this.mCountryCodes["SN"] = "SENEGAL";
         this.mCountryCodes["RS"] = "SERBIA";
         this.mCountryCodes["SC"] = "SEYCHELLES";
         this.mCountryCodes["SL"] = "SIERRA LEONE";
         this.mCountryCodes["SG"] = "SINGAPORE";
         this.mCountryCodes["SX"] = "SINT MAARTEN (DUTCH PART)";
         this.mCountryCodes["SK"] = "SLOVAKIA";
         this.mCountryCodes["SI"] = "SLOVENIA";
         this.mCountryCodes["SB"] = "SOLOMON ISLANDS";
         this.mCountryCodes["SO"] = "SOMALIA";
         this.mCountryCodes["ZA"] = "SOUTH AFRICA";
         this.mCountryCodes["GS"] = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS";
         this.mCountryCodes["SS"] = "SOUTH SUDAN";
         this.mCountryCodes["ES"] = "SPAIN";
         this.mCountryCodes["LK"] = "SRI LANKA";
         this.mCountryCodes["SD"] = "SUDAN";
         this.mCountryCodes["SR"] = "SURINAME";
         this.mCountryCodes["SJ"] = "SVALBARD AND JAN MAYEN";
         this.mCountryCodes["SZ"] = "SWAZILAND";
         this.mCountryCodes["SE"] = "SWEDEN";
         this.mCountryCodes["CH"] = "SWITZERLAND";
         this.mCountryCodes["SY"] = "SYRIAN ARAB REPUBLIC";
         this.mCountryCodes["TW"] = "TAIWAN, PROVINCE OF CHINA";
         this.mCountryCodes["TJ"] = "TAJIKISTAN";
         this.mCountryCodes["TZ"] = "TANZANIA, UNITED REPUBLIC OF";
         this.mCountryCodes["TH"] = "THAILAND";
         this.mCountryCodes["TL"] = "TIMOR-LESTE";
         this.mCountryCodes["TG"] = "TOGO";
         this.mCountryCodes["TK"] = "TOKELAU";
         this.mCountryCodes["TO"] = "TONGA";
         this.mCountryCodes["TT"] = "TRINIDAD AND TOBAGO";
         this.mCountryCodes["TN"] = "TUNISIA";
         this.mCountryCodes["TR"] = "TURKEY";
         this.mCountryCodes["TM"] = "TURKMENISTAN";
         this.mCountryCodes["TC"] = "TURKS AND CAICOS ISLANDS";
         this.mCountryCodes["TV"] = "TUVALU";
         this.mCountryCodes["UG"] = "UGANDA";
         this.mCountryCodes["UA"] = "UKRAINE";
         this.mCountryCodes["AE"] = "UNITED ARAB EMIRATES";
         this.mCountryCodes["GB"] = "UNITED KINGDOM";
         this.mCountryCodes["US"] = "UNITED STATES";
         this.mCountryCodes["UM"] = "UNITED STATES MINOR OUTLYING ISLANDS";
         this.mCountryCodes["UY"] = "URUGUAY";
         this.mCountryCodes["UZ"] = "UZBEKISTAN";
         this.mCountryCodes["VU"] = "VANUATU";
         this.mCountryCodes["VE"] = "VENEZUELA, BOLIVARIAN REPUBLIC OF";
         this.mCountryCodes["VN"] = "VIET NAM";
         this.mCountryCodes["VG"] = "VIRGIN ISLANDS, BRITISH";
         this.mCountryCodes["VI"] = "VIRGIN ISLANDS, U.S.";
         this.mCountryCodes["WF"] = "WALLIS AND FUTUNA";
         this.mCountryCodes["EH"] = "WESTERN SAHARA";
         this.mCountryCodes["YE"] = "YEMEN";
         this.mCountryCodes["ZM"] = "ZAMBIA";
         this.mCountryCodes["ZW"] = "ZIMBABWE";
      }
      
      public static function instance() : CountryCodes
      {
         if(sCountryCode == null)
         {
            sCountryCode = new CountryCodes();
         }
         return sCountryCode;
      }
      
      public function getCountryName(countryCode:String) : String
      {
         return this.mCountryCodes[countryCode];
      }
   }
}
